void sum()
{
	int a,b,c;

	printf("enter a:");
	scanf("%d",&a);
	printf("enter b:");
	scanf("%d",&b);

		c=a+b;

	printf("sum=%d",c);

}
void sub()
{
	int a,b,c;

	printf("enter a:");
	scanf("%d",&a);
	printf("enter b:");
	scanf("%d",&b);

		c=a-b;

	printf("sub=%d",c);

}
void mul()
{
	int a,b,c;

	printf("enter a:");
	scanf("%d",&a);
	printf("enter b:");
	scanf("%d",&b);

		c=a*b;

	printf("mul=%d",c);

}
void div()
{
	int a,b,c;

	printf("enter a:");
	scanf("%d",&a);
	printf("enter b:");
	scanf("%d",&b);

		c=a/b;

	printf("div=%d",c);
}